---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: debian-7.8

suites:
  - name: default
    run_list:
      - recipe[statsd::default]
    attributes:
